name: Data Collection and Processing

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Fetch Kubernetes history
        working-directory: ./scripts/shell
        run: |
          chmod +x ./fetch.sh
          ./fetch.sh
        shell: bash

      - name: Fetch Pull Requests
        working-directory: ./scripts/shell
        run: |
          chmod +x ./fetch_pr.sh 1000
          ./fetch_pr.sh
        shell: bash

      - name: Collect all existing files
        working-directory: ./scripts/shell
        run: |
          chmod +x ./collect_all_files.sh
          ./collect_all_files.sh
        shell: bash

      - name: Format data
        working-directory: ./scripts/python
        run: |
          python format.py
        shell: bash

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: |
            data/output/
            data/cache/
          retention-days: 7

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --staged --quiet || (git commit -m "Auto-update data via GitHub Actions" && git push)
