name: Sync to gh-pages

on:
  workflow_run:
    workflows: ["Data Collection and Processing"]
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to gh-pages and merge
        run: |
          git fetch origin gh-pages
          git checkout -B gh-pages origin/gh-pages
          git merge origin/develop --no-edit
          git push origin gh-pages
